sqlite:
  adapter: sqlite3
  database: ":memory:"

mysql:
  adapter: mysql2
  username: root
  password:
  database: acts_as_list

postgresql:
  adapter: postgresql
  username: postgres
  password:
  database: acts_as_list
  min_messages: ERROR